/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andy
 */
import java.net.URL;
import java.text.DecimalFormat;
import java.io.*;
import java.util.*;
import java.awt.Toolkit;
import java.awt.image.*;
import javax.swing.*;
import javax.imageio.ImageIO;

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        cnyLabel = new javax.swing.JLabel();
        eurLabel = new javax.swing.JLabel();
        jpyLabel = new javax.swing.JLabel();
        enterField = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTF1 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTF2 = new javax.swing.JTextField();
        jTF3 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTF4 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTF5 = new javax.swing.JTextField();
        jTF6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        cdLabel = new javax.swing.JLabel();
        wtLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/kyo_tux_delikate_burn-7.png")));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel3.setBackground(java.awt.Color.white);

        jButton2.setBackground(java.awt.Color.black);
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Currency Exchange Rate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        timeLabel.setBackground(java.awt.Color.white);

        cnyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cnyLabel.setText("USD/CNY");

        eurLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eurLabel.setText("USD/EUR");

        jpyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jpyLabel.setText("USD/JPY");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(eurLabel)
                    .addComponent(cnyLabel)
                    .addComponent(jpyLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(133, 133, 133))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(enterField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(enterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cnyLabel)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addComponent(eurLabel)
                .addGap(18, 18, 18)
                .addComponent(jpyLabel)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Currency Live", jPanel3);

        jPanel2.setBackground(java.awt.Color.white);

        jButton1.setBackground(java.awt.Color.black);
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mm", "cm", "m", "km", "ft", "mile" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mm", "cm", "m", "km", "ft", "mile" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "˚C", "˚F", "Kelvin" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "˚C", "˚F", "Kelvin" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "kg", "lb", "oz" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "kg", "lb", "oz" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, 0, 57, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF6, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jTF2)
                    .addComponent(jTF4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(116, 116, 116))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Unit Converter", jPanel2);

        jPanel1.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stock Market", jPanel1);

        jPanel4.setBackground(java.awt.Color.white);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sign-Refresh-icon copy.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cityLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cityLabel.setText("City:");

        tempLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tempLabel.setText("Temp:");

        cdLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cdLabel.setText("Condition:");

        wtLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        wtLabel.setText("Time:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(iconLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addGap(99, 99, 99)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(47, 47, 47)
                        .addComponent(iconLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(wtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Weather", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:   
        DecimalFormat f = new DecimalFormat("#####0.#######");
        jTF2.setText("");
        jTF4.setText("");
        jTF6.setText("");
        if (!jTF1.getText().equals("")) {
            Object selected1 = jComboBox2.getSelectedItem();
            Object selected2 = jComboBox3.getSelectedItem();
            Double tf1 = new Double(jTF1.getText());
            
            if (selected1 == selected2) {
                jTF2.setText(jTF1.getText());
            }
            //mm
            if (selected1 == "mm") {
                if (selected2 == "cm") {
                    jTF2.setText(f.format(tf1 / 10));
                }//mm to cm               
                if (selected2 == "m") {
                    jTF2.setText(f.format(tf1 / 100));
                }// mm to m               
                if (selected2 == "km") {
                    jTF2.setText(f.format(tf1 / 100000));
                }// mm to km               
                if (selected2 == "ft") {
                    jTF2.setText(f.format(tf1 * 0.00328));
                }// mm to ft               
                if (selected2 == "mile") {
                    jTF2.setText(f.format(tf1 / 1609344));
                }//mm to mile
                if(selected2 =="inch"){
                    jTF2.setText(f.format(tf1*0.0393701));
                }//mm to inch
            }// mm

            //cm
            if (selected1 == "cm") {
                if (selected2 == "mm") {
                    jTF2.setText(f.format(tf1 * 10));
                }//cm to mm               
                if (selected2 == "m") {
                    jTF2.setText(f.format(tf1 / 10));
                }// cm to m               
                if (selected2 == "km") {
                    jTF2.setText(f.format(tf1 / 10000));
                }// cm to km               
                if (selected2 == "ft") {
                    jTF2.setText(f.format(tf1 * 0.0328));
                }// cm to ft               
                if (selected2 == "mile") {
                    jTF2.setText(f.format(tf1 / 160934.4));
                }//cm to mile           
                if (selected2 == "inch") {
                    jTF2.setText(f.format(tf1 *0.393701));
                }//cm to inch      
            }// cm

            //m
            if (selected1 == "m") {
                if (selected2 == "cm") {
                    jTF2.setText(f.format(tf1 * 10));
                }//m to cm               
                if (selected2 == "mm") {
                    jTF2.setText(f.format(tf1 * 100));
                }// m to mm               
                if (selected2 == "km") {
                    jTF2.setText(f.format(tf1 / 1000));
                }// m to km               
                if (selected2 == "ft") {
                    jTF2.setText(f.format(tf1 * 3.28084));
                }// m to ft               
                if (selected2 == "mile") {
                    jTF2.setText(f.format(tf1 / 1609.344));
                }//m to mile      
                if (selected2 == "inch") {
                    jTF2.setText(f.format(tf1 *39.3701));
                }//m to inch  
            }// m

            //km
            if (selected1 == "km") {
                if (selected2 == "cm") {
                    jTF2.setText(f.format(tf1 * 10000));
                }//km to cm               
                if (selected2 == "mm") {
                    jTF2.setText(f.format(tf1 * 100000));
                }// km to mm               
                if (selected2 == "m") {
                    jTF2.setText(f.format(tf1 * 1000));
                }// km to m               
                if (selected2 == "ft") {
                    jTF2.setText(f.format(tf1 * 3280.83));
                }// km to ft               
                if (selected2 == "mile") {
                    jTF2.setText(f.format(tf1 / 1.609344));
                }//km to mile              
                if (selected2 == "inch") {
                    jTF2.setText(f.format(tf1 * 39370.1));
                }//km to inch  
            }// km

            //ft
            if (selected1 == "ft") {
                if (selected2 == "cm") {
                    jTF2.setText(f.format(tf1 * 30.38));
                }//ft to cm               
                if (selected2 == "mm") {
                    jTF2.setText(f.format(tf1 * 304.8));
                }// ft to mm               
                if (selected2 == "km") {
                    jTF2.setText(f.format(tf1 * 0.0003048));
                }// ft to km               
                if (selected2 == "m") {
                    jTF2.setText(f.format(tf1 * 0.3048));
                }// ft to m               
                if (selected2 == "mile") {
                    jTF2.setText(f.format(tf1 * 0.000189394));
                }//ft to mile    
                if (selected2 == "inch") {
                    jTF2.setText(f.format(tf1 * 12));
                }//ft to inch
            }// ft

            //mile
            if (selected1 == "mile") {
                if (selected2 == "cm") {
                    jTF2.setText(f.format(tf1 * 16093.44));
                }//mile to cm               
                if (selected2 == "mm") {
                    jTF2.setText(f.format(tf1 * 160934.4));
                }// mile to mm               
                if (selected2 == "km") {
                    jTF2.setText(f.format(tf1 * 1.609));
                }// mile to km               
                if (selected2 == "m") {
                    jTF2.setText(f.format(tf1 * 1609.344));
                }// mile to m               
                if (selected2 == "ft") {
                    jTF2.setText(f.format(tf1 * 5280));
                }//mile to ft       
                if (selected2 == "inch") {
                    jTF2.setText(f.format(tf1 * 63360));
                }//mile to inch  
            }// mile 
            
            //inch
            if (selected1 == "inch") {
                if (selected2 == "cm") {
                    jTF2.setText(f.format(tf1 * 2.54));
                }//inch to cm               
                if (selected2 == "mm") {
                    jTF2.setText(f.format(tf1 * 25.4));
                }// inch to mm               
                if (selected2 == "km") {
                    jTF2.setText(f.format(tf1 * 0.0000254));
                }// inch to km               
                if (selected2 == "m") {
                    jTF2.setText(f.format(tf1 * 0.0254));
                }// inch to m               
                if (selected2 == "ft") {
                    jTF2.setText(f.format(tf1 * 0.0833333));
                }//inch to ft       
                if (selected2 == "mile") {
                    jTF2.setText(f.format(tf1 * 0.000015783));
                }//inch to mile  
            }// inch
        }

        // Temperature Conversion 
        if (!jTF3.getText().equals("")) {
            Object tempSelected1 = jComboBox4.getSelectedItem();
            Object tempSelected2 = jComboBox5.getSelectedItem();
            Double tf2 = new Double(jTF3.getText());
            
            if (tempSelected1 == tempSelected2) {
                jTF4.setText(jTF3.getText());
            }
            if (tempSelected1 == "˚C") {
                if (tempSelected2 == "˚F") {
                    jTF4.setText(f.format(tf2 * 1.8 + 32));
                }
                if (tempSelected2 == "Kelvin") {
                    jTF4.setText(f.format(tf2 + 273));
                }
            }

            if (tempSelected1 == "˚F") {
                if (tempSelected2 == "˚C") {
                    jTF4.setText(f.format((tf2 - 32) / 1.8));
                }
                if (tempSelected2 == "Kelvin") {
                    jTF4.setText(f.format((tf2 - 32) / 1.8 + 273));
                }
            }
        }//Temp
        
        //Weight Conversion
        if (!jTF5.getText().equals("")) {
            Object tempSelected3 = jComboBox1.getSelectedItem();
            Object tempSelected4 = jComboBox6.getSelectedItem();
            Double tf3 = new Double(jTF5.getText());
            
            if(tempSelected3 == tempSelected4)
                jTF6.setText(jTF5.getText());
            //g
            if(tempSelected3 == "g"){
                if(tempSelected4 == "kg" ){
                    jTF6.setText(f.format(tf3 * 0.001));
                }//g to kg
                if(tempSelected4 == "lb"){
                    jTF6.setText(f.format(tf3 * 0.00220462));
                }//g to lb
                if(tempSelected4 == "oz"){
                    jTF6.setText(f.format(tf3 * 0.035274));
                }//g to oz                
            }//g
            
            //kg
            if(tempSelected3 == "kg"){
                if(tempSelected4 == "g" ){
                    jTF6.setText(f.format(tf3 * 1000));
                }//kg to g
                if(tempSelected4 == "lb"){
                    jTF6.setText(f.format(tf3 * 2.20462));
                }//kg to lb
                if(tempSelected4 == "oz"){
                    jTF6.setText(f.format(tf3 * 35.274));
                }//kg to oz                
            }//kg
            
            //lb
            if(tempSelected3 == "lb"){
                if(tempSelected4 == "g" ){
                    jTF6.setText(f.format(tf3 * 453.592));
                }//lg to g
                if(tempSelected4 == "kg"){
                    jTF6.setText(f.format(tf3 * 0.453592));
                }//lg to kg
                if(tempSelected4 == "oz"){
                    jTF6.setText(f.format(tf3 * 16));
                }//lb to oz                
            }//lb
            
            //oz
            if(tempSelected3 == "oz"){
                if(tempSelected4 == "g" ){
                    jTF6.setText(f.format(tf3 * 28.3495));
                }//oz to g
                if(tempSelected4 == "kg"){
                    jTF6.setText(f.format(tf3 * 0.0283495));
                }//oz to kg
                if(tempSelected4 == "lb"){
                    jTF6.setText(f.format(tf3 * 0.0625));
                }//oz to lb                
            }//oz
        }//Weight

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:        
        GetData data = new GetData();
        DecimalFormat f = new DecimalFormat(".##");
        String[] result = data.readCurrency();
        Double cny =new Double(result[0]);
        Double eur =new Double(result[1]);
        Double jpy =new Double(result[2]);
        String requestTime = result[3];
        if((!enterField.getText().isEmpty())){
            Double exchangeRate = new Double(enterField.getText());
            cnyLabel.setText(f.format(cny*exchangeRate) + " USD/CNY");
            eurLabel.setText(f.format(eur*exchangeRate) + " USD/EUR");
            jpyLabel.setText(f.format(jpy*exchangeRate) + " USD/JPY");
            timeLabel.setText("<html><p>Updated Time:</p>" + requestTime + "</html>");
        }else{
            cnyLabel.setText(cny + " USD/CNY");
            eurLabel.setText(eur + " USD/EUR");
            jpyLabel.setText(jpy + " USD/JPY");
            timeLabel.setText("<html><p>Updated Time:</p>" + requestTime + "</html>");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        GetData data = new GetData();
        String[] result = data.readWeather();
        try {
            URL url = new URL(result[0]);
            BufferedImage img = ImageIO.read(url);
            ImageIcon icon = new ImageIcon(img);
            iconLabel.setIcon(icon);
            cityLabel.setText("City: " + result[1]);
            tempLabel.setText("Temp: " + result[2]);
            cdLabel.setText("Condition: " + result[3]);
            wtLabel.setText("Time: " + result[4]);

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cdLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel cnyLabel;
    private javax.swing.JTextField enterField;
    private javax.swing.JLabel eurLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF2;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private javax.swing.JTextField jTF5;
    private javax.swing.JTextField jTF6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jpyLabel;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel wtLabel;
    // End of variables declaration//GEN-END:variables
}
